# Generated by Django 3.2.10 on 2022-02-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discountsapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
