# Generated by Django 3.2.10 on 2021-12-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discountsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='inventory',
            new_name='inventory_id',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='categories',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='inventory_category',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='inventory_category',
            old_name='inventory',
            new_name='inventory_id',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='store',
            new_name='store_id',
        ),
    ]
