# Generated by Django 3.2.10 on 2021-12-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discountsapi', '0002_auto_20211221_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='inventory_id',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='inventory_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='inventory_category',
            old_name='inventory_id',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='store_id',
            new_name='store',
        ),
    ]
