# Generated by Django 3.2.10 on 2022-01-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountsapi', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
    ]
