# Generated by Django 3.2.10 on 2022-01-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discountsapi', '0005_inventory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='image',
        ),
    ]
