# Generated by Django 3.2.10 on 2022-01-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discountsapi', '0007_auto_20220108_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
